name: dotstar
description: Application to control sdrip from mobiles.

dependencies:
  flutter:
    sdk: flutter  
  
  # cupertino_icons: ^0.1.0
  http: any
  # flutter_launcher_icons: ^0.2.0
  # rxdart: ^0.16.0+1
  flutter_colorpicker: any
  mdns:
    git:
      url: git://github.com/gizmomogwai/flutter_mdns.git
      ref: development
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/strip.jpg

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true
