name: dotstar
description: Application to control sdrip from mobiles.

dependencies:
  flutter:
    sdk: flutter  
  
  http: any
  flutter_colorpicker: any
  flutter_launcher_icons: ^0.2.1
  mdns:
    git:
      url: git://github.com/gizmomogwai/flutter_mdns.git
      ref: development
#    path: /Users/gizmo/Dropbox/Documents/_projects/_dart/flutter_mdns

  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/strip.jpg

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true
