name: dotstar
description: Application to control sdrip from mobiles.

dependencies:
  flutter:
    sdk: flutter  
  
  cupertino_icons: ^0.1.0
  http: ^0.11.3
  flutter_launcher_icons: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true
